#!/bin/sh

base="Prints"
day=$(date +%y%m%d)
time=$(date +%H%M%S)
dir="$base/$day"
file="$dir/${1}${time}.txt"

mkdir -p "$dir"

if [ -e "$file" ]; then
  file="$dir/${1}${time}-1.txt"
fi

cp printout.txt "$file"