#!/bin/bash
# cleanR65 - clean files bevore 'git add'

cd ~/Projects/R65/R65-Emulator
rm Files/test*.pas
rm Listings/test*.txt
mv Files/*.pas Pascal 2>/dev/null
mv Files/*.asm Assembler 2>/dev/null
mv Files/*.help Help 2>/dev/null

git status
