#!/bin/bash
# cleanup files for git commit/push

rm Files/test*.pas
rm Listings/test*.txt
mv Files/*.pas Pascal 2>/dev/null
mv Files/*.asm Assembler 2>/dev/null
mv Files/*.asm Assembler 2>/dev/null
mv Files/*.help Help 2>/dev/null

git status
