#!/bin/bash
# cleanup files for git commit/push

mv Files/test*.pas Savetests 2>/dev/null
mv Listings/test*.txt Savetests 2>/dev/null
mv Files/*.pas Pascal 2>/dev/null
mv Files/*.asm Assembler 2>/dev/null

git status
