#!/bin/bash
# cleanR65 - clean files bevore 'git add'

cd /home/rricharz/Projects/R65/R65-Emulator
rm Files/test*.pas
rm Listings/test*.txt
mv Files/*.pas Pascal
mv Files/*.asm Assembler
mv Files/*.help Help

git status
