#!/bin/bash

IN="printout.txt"
OUT="printout.pdf"

NAME=$(grep -m1 -Eo '[A-Za-z][A-Za-z0-9_]*[[:space:]]*\(1\)' "$IN" \
  | sed 's/[[:space:]]*(1)//' \
  | tr 'A-Z' 'a-z')

if [ -n "$NAME" ]; then
    mkdir -p ../Manuals
    OUT="../Manuals/$NAME.pdf"
fi

echo "Creating $OUT..."

enscript -B -f Courier10 -o - "$IN" | ps2pdf - "$OUT"

echo "Done."