#!/bin/bash

# R65 tek4010 launcher
# mode bit 0: full vertical window
# mode bit 1: fast drawing

TEK="$HOME/bin/tek4010"
MODE="$1"

ARGS="-nokey"

if (( MODE & 1 )); then
    ARGS="$ARGS -fullv"
else
    ARGS="$ARGS -half"
fi

if (( MODE & 2 )); then
    ARGS="$ARGS -fast"
fi

exec "$TEK" $ARGS tail -f printout.txt